version: '3.8'
services:
    main:
        build:
            context: .
            dockerfile: Dockerfile
        command: 'node index.js'
        ports:
            - 8080:8080
        depends_on:
            - db
    db:
        platform: linux/x86_64
        image: mysql:8.0
        environment:
            MYSQL_DATABASE: cr-js-db
            MYSQL_USER: admin
            MYSQL_ROOT: root
            MYSQL_PASSWORD: password
            MYSQL_ROOT_PASSWORD: password
        volumes:
            - ./storage/dbdata:/var/lib/mysql
        ports:
            - 3306:3306
